version: "3.7"
services:
  web:
    image: docker.io/chenhung0506/python-grpc:latest
    container_name: python-grpc
    # environment:
    #   - PORT=22222
    volumes:
      - ~/volumes/python-grpc:/usr/src/app/logs
    restart: always
    ports: 
      - "50051:50051"
    env_file:
      - dev.env
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx

